# Document title

site_name: Clinical Cancer Genomics Course
site_description: Project documentation with Markdown.
theme:
  name: material
  language: en
  direction: ltr

  logo: assets/img/KI_digital_logotyp_negativ_RGB.svg
  favicon: assets/img/favicon.ico
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    # - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.expand
    # - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    - navigation.top
    # - navigation.tracking
    # - navigation.footer
    # - header.autohide
    - content.code.annotate
    - content.tabs.link
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    # - toc.follow


  palette:
    scheme: default

  font: false    
  # font:
  #   text: Roboto
  #   code: Roboto Mono

copyright: Copyright &copy; 2023, Johan Lindberg et. al., MEB, Karolinska Institutet, All rights reserved.

extra:
  generator: false


extra_css:
  - assets/css/extra.css

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Course Details: index.md
  - Schedule: schedule.md
  - Lectures: lectures/lectures.md
  - AWS Instances Login: aws/aws_ec2_instances.md
  # - Pre-course setup:
  #   - Installation : installation.md
  #   - Download Files:
  #     - Reference: references.md
  #     - Annotation: annotations.md
  - Lab Session:
      - Day 1:
        - Basic Unix: lab_session/basic_unix.md
        - AWK : lab_session/basics_awk.md
        - Workspace - AWS : lab_session/aws_env.md
        - R for Bioinformatics: lab_session/R_for_bioinformatics.md
        - Command Line Usage in Real Life: lab_session/real_life_example_cli.md
        - ggplot tutorial: lab_session/real_life_example_cli.md
      - Day 2:
        - Human Genome: lab_session/human_genome.md
        - Annotation: lab_session/annotation_files.md
        - Processing of DNA sequencing data: lab_session/processing_of_dna.md
        - Introduction to IGV: lab_session/intro_igv.md
      - Day 3:
        - Variant Calling: lab_session/variant_calling.md
      - Day 4:
        - Structural Variants: lab_session/structural_variation.md
        - Copy Number Variations: lab_session/analysis_of_cnv.md
        - RNAseq: lab_session/processing_of_rnaseq.md
      - Day 5:
        - Joint Curation: lab_session/joint_curation.md
        - Genomic Alterations Interpretation: lab_session/genomic_alteration_interpretation_exe.md   
